# Generated by Django 3.1 on 2020-08-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=50)),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('rating_count', models.IntegerField()),
                ('avg_rating', models.CharField(max_length=10)),
                ('director', models.TextField(default='{}')),
                ('actor', models.TextField(default='[]')),
                ('published_on', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
